title: Svatba Verča ♥️ Honza
author: Honza & Verča
description: Naše svatba
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yous.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: cz
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - vendor

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

